version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Sadie.Networking.Writers"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    target-branch: "develop"
    allow:
      - dependency-name: "Sadie.API"
      - dependency-name: "Sadie.Db"
      - dependency-name: "Sadie.Networking.Serialization"
